name: Cargo-C StaticLib Build

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 0:00
  workflow_dispatch:

permissions:
  contents: write   # 允許上傳 release

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: 
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Package
        run: sudo apt-get update && sudo apt-get install -y nasm

      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Build staticlib with cargo-c
        run: |
          cargo cbuild --release --target ${{ matrix.target }} --library-type staticlib

      - name: Package artifacts
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/*.lib dist/ || true
          cp target/${{ matrix.target }}/release/*.a dist/ || true
          cp -r target/${{ matrix.target }}/release/capi dist/capi
          zip -r rav1e-${{ matrix.target }}.zip dist
        shell: bash

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: rav1e-${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
