name: Cargo-C StaticLib Build

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 UTC 0:00
  workflow_dispatch:

permissions:
  contents: write   # 允許上傳 release

jobs:
  build-x86_64:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Set up NASM
        uses: ilammy/setup-nasm@v1
        
      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Build staticlib with cargo-c
        run: |
          cargo cbuild --release --target x86_64-pc-windows-msvc --library-type staticlib

      - name: Package artifacts
        shell: pwsh
        run: |
          # 建立資料夾
          New-Item -ItemType Directory -Path dist -Force | Out-Null

          # 複製 *.lib 和 *.a 檔案
          Copy-Item -Path "target\x86_64-pc-windows-msvc\release\*.lib" -Destination dist -ErrorAction SilentlyContinue
          Copy-Item -Path "target\x86_64-pc-windows-msvc\release\*.a"   -Destination dist -ErrorAction SilentlyContinue

          # 複製 capi 資料夾
          Copy-Item -Path "target\x86_64-pc-windows-msvc\release\capi" -Destination "dist\capi" -Recurse -Force

          # 壓縮成 zip
          Compress-Archive -Path dist\* -DestinationPath rav1e-x86_64.zip -Force

      - name: Upload Clang build artifact
        uses: actions/upload-artifact@v4
        with:
          name: rav1e-x86_64
          path: ${{ GITHUB_WORKSPACE }}\dist\rav1e-x86_64.zip

  build-aarch64:
    runs-on: windows-11-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc

      - name: Install LLVM
        uses: llvm/llvm-project@main
        with:
          toolchain: clang
        
      - name: Install cargo-c
        run: cargo install cargo-c

      - name: Build staticlib with cargo-c
        run: |
          set CC=clang-cl
          set CXX=clang-cl
          cargo cbuild --release --target aarch64-pc-windows-msvc --library-type staticlib

      - name: Package artifacts
        shell: pwsh
        run: |
          # 建立資料夾
          New-Item -ItemType Directory -Path dist -Force | Out-Null

          # 複製檔案 (*.lib 和 *.a)
          Copy-Item -Path "target\aarch64-pc-windows-msvc\release\*.lib" -Destination dist -ErrorAction SilentlyContinue
          Copy-Item -Path "target\aarch64-pc-windows-msvc\release\*.a"   -Destination dist -ErrorAction SilentlyContinue

          # 複製 capi 資料夾
          Copy-Item -Path "target\aarch64-pc-windows-msvc\release\capi" -Destination "dist\capi" -Recurse -Force

          # 壓縮成 zip
          Compress-Archive -Path dist\* -DestinationPath rav1e-aarch64.zip -Force

      - name: Upload Clang build artifact
        uses: actions/upload-artifact@v4
        with:
          name: rav1e-aarch64
          path: ${{ GITHUB_WORKSPACE }}\dist\rav1e-aarch64.zip
  upload-release:
    runs-on: ubuntu_latest
    steps:
      - name: Download Artifact
        
